version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales data for greenweez company
        columns:
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: orders_id
            tests:
              - not_null
          - name: pdt_id
            tests:
              - not_null
          - name: revenue
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE
            tests:
              - not_null
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: orders id
            tests:
             - not_null
          - name: shipping_fee
            description: shipping fee
            tests:
             - not_null
          - name: shipping_fee_1
            description: shippingfee1
            tests:
             - not_null
          - name: logCost
            tests:
              - not_null
          - name: ship_cost
            tests:
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook  

models:
      - name: int_campaigns
        columns:
          - name: paid_source
            tests:
              - not_null
          - name: campaign_name
            tests:
              - not_null

      - name: int_campaigns_day
        columns:
          - name: date_date
            tests:
              - not_null
          - name: ads_cost  
            tests:
              - not_null
          - name: ads_impression
            tests:
              - not_null
          - name: ads_clicks
            tests:
              - not_null

      - name: finance_campaigns_day
        description: global kpi
        columns:
          - name: ads_margin
            description: operational_margin - ads_cost
            tests:
              - not_null
          - name: average_basket
            description: günlük ortalama sepet tutarı
            tests:
              - not_null
      

