version: 2

sources:
  - name: raw
    schema: raw_gz_data
    tables:
      - name: sales
        identifier: raw_sales
        description: sales data for greenweez company
        columns:
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: orders_id
            tests:
              - not_null
          - name: pdt_id
            tests:
              - not_null
          - name: revenue
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null
      - name: products
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE
            tests:
              - not_null
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: orders id
            tests:
             - not_null
          - name: shipping_fee
            description: shipping fee
            tests:
             - not_null
          - name: shipping_fee_1
            description: shippingfee1
            tests:
             - not_null
          - name: logCost
            tests:
              - not_null
          - name: ship_cost
            tests:
              - not_null
